FROM node:16.14.2-alpine3.15 as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci 
COPY app.js ./

FROM node:16.14.2-alpine3.15
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
EXPOSE 3000
USER node
CMD ["node","app.js"]